### ISSUE TITLE
Script should exit with a non zero status on error

### ISSUE THREAD

**Issue by giacmir** [sk-/html-linter#10]
To use this script with CI tools it would be useful if it could exit with a non zero status in case it detects errors.

**Comment by sk-** [comment]
It does exit with a non-zero code in case of errors. Could you specify which version are you using?

**Comment by giacmir** [comment]
I confirm this, for me it exits with 0 when errors are present. I'm using version 0.3.0 installed from pip, (shell is zsh, but I don't think it is related).
